config/routes.rb
Rollpoll::Application.routes.draw do

  resources :topics
  resources :sessions

  resources :questions, except: [:edit, :destroy] do
    get :next, on: :collection
    get :ninja, on: :collection
    resources :answers, only: :show do
      get :vote, on: :member, as: :vote
    end
  end

  resources :users, only: [:new, :index, :create, :show] do
    get :username_check, on: :collection
    get :history, on: :collection
  end

  match '/about' => "pages#about", as: :about
  match '/login' => "sessions#new", as: :login
  match '/logout' => "sessions#destroy", as: :logout
  match '/registration' => "users#new", as: :registration
  match '/users/username_check/:uname' => 'users#username_check'


  namespace :admin do
    resources :administrators
    resources :questions
    resources :users
    resources :sessions

    match '/login' => "sessions#new", as: :login
    match '/logout' => "sessions#destroy", as: :logout

    root :to => 'users#index'
  end

  root :to => 'pages#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base

  has_secure_password

  attr_accessible :name, :username, :password, :password_confirmation

  validates :username, uniqueness: true
  validates :name, :username, :password, :password_confirmation, presence: true

end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::ApplicationController
  inherit_resources
end

app/views/admin/administrators/_form.html.haml
.form-horizontal
  = simple_form_for([:admin, @administrator]) do |f|

    .form-inputs
      .control-group
        = f.label :name, class: 'control-label'
        .controls= f.input :name, label: false

      .control-group
        = f.label :username, class: 'control-label'
        .controls= f.input :username, label: false

      .control-group
        = f.label :password, class: 'control-label'
        .controls= f.input :password, label: false

      .control-group
        = f.label :password_confirmation, class: 'control-label'
        .controls= f.input :password_confirmation, label: false

    .form-actions
      = f.button :submit, class: 'btn btn-success'

app/views/admin/administrators/edit.html.haml
%h1 Editing Admin

= render 'form'

.buttons
  = link_to 'View Admin', admin_administrator_path(@administrator), class: 'btn btn-primary'
  = link_to 'Delete Admin', admin_administrator_path(@administrator), :method => :delete, :confirm => "Are you sure?", class: 'btn btn-danger'

app/views/admin/administrators/index.html.haml
%h1 All Administrators

= link_to 'New Administrator', new_admin_administrator_path, class: 'btn btn-large btn-info pull-right'

%table.table
  %thead
    %tr
      %th Name
      %th Username
      %th{width: '30%'} Actions

  - @administrators.each do |admin|
    %tr
      %td= admin.name
      %td= admin.username
      %td
        = link_to 'Show', admin_administrator_path(admin), class: 'btn btn-primary'
        = link_to 'Edit', edit_admin_administrator_path(admin), class: 'btn btn-warning'
        = link_to 'Destroy', admin_administrator_path(admin), :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger'

app/views/admin/administrators/new.html.haml
%h1 New Admin

= render 'form'

app/views/admin/administrators/show.html.haml
%h1 Admin ##{@administrator.id}

.nice_spacings
  .group
    .title Name:
    .body= @administrator.name

  .group
    .title Username:
    .body= @administrator.username

  .group
    .title Date Created:
    .body= @administrator.created_at.to_s(:date)


.left_buttons= link_to 'Back', admin_administrators_path, class: 'btn btn-inverse'