config/routes.rb
Rollpoll::Application.routes.draw do

  resources :topics
  resources :sessions

  resources :questions, except: [:edit, :destroy] do
    get :next, on: :collection
    get :ninja, on: :collection
    resources :answers, only: :show do
      get :vote, on: :member, as: :vote
    end
  end

  resources :users, only: [:new, :index, :create, :show] do
    get :username_check, on: :collection
    get :history, on: :collection
  end

  match '/about' => "pages#about", as: :about
  match '/login' => "sessions#new", as: :login
  match '/logout' => "sessions#destroy", as: :logout
  match '/registration' => "users#new", as: :registration
  match '/users/username_check/:uname' => 'users#username_check'


  namespace :admin do
    resources :administrators
    resources :questions
    resources :users
    resources :sessions

    match '/login' => "sessions#new", as: :login
    match '/logout' => "sessions#destroy", as: :logout

    root :to => 'users#index'
  end

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :questions
  has_many :votes

  attr_accessible :dob, :email, :gender, :password_digest, :zip, :password, :password_confirmation, :username

  # validates :username, :email, :password, :password_confirmation, :zip, :gender, :dob, presence: true
  validates :username, :email, presence: true
  validates :username, :uniqueness => true
  validates :email, email: true

  validates :password, :password_confirmation, presence: true, :if => :is_new_record
  validates :password, :confirmation => true, :if => :is_new_record



  private
    def is_new_record
      new_record?
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  inherit_resources
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :new, :index, :create, :show

  before_filter :authenticate_user!, only: [:show, :history]

  def username_check
    user = User.where("username = ?", params[:uname]).first
    if user.present?
      render :json => { free: false }
    else
      render :json => { free: true }
    end
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      session[:last_page_load] = Time.now
      flash[:success] = "Your account has been created successfully."
      redirect_to root_path
    else
      render :action => "new"
    end
  end

  def show
    authenticate_user!
  end

  def history
    authenticate_user!
    @questions_asked = Question.where(:user_id => current_user.id).order("created_at desc")
    user_votes = Vote.where(:user_id => current_user.id).map(&:question_id)
    @questions_answered = Question.find(user_votes).sort_by(&:created_at).reverse
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.slim_form
  = simple_form_for @user do |f|
    = f.input :username, label: "username:"
    = f.input :email, label: "email:"
    = f.input :password, label: "password:", required: true
    = f.input :password_confirmation, label: 'confirm password:', required: true
    =# f.input :zip, label: false, placeholder: "zip *"
    =# f.input :dob, label: "dob", wrapper_html: { class: 'select_wrapper' }, :start_year => Time.now.year - 60, :end_year => Time.now.year - 10, order: [:month, :day, :year], :prompt => true
    =# f.input :gender, :collection => ['Male', 'Female'], label: 'gender', wrapper_html: { class: 'select_wrapper' }
    .submit
      = f.submit 'REGISTER', class: "submit"

:javascript
  $(document).ready(function() {

    $(":input").blur(function() {

      var this_id = $(this).attr('id');

      if (this_id == 'user_email') {
        if ( $(this).val() != '' && validateEmail($(this).val())) {
          $(this).addClass('green');
        } else {
          $(this).removeClass('green').addClass('red');
        }

      } else if (this_id == 'user_password_confirmation') {
        if ($('#user_password_confirmation').val() == $('#user_password').val()) {
          $('#user_password_confirmation').addClass('green');
        } else {
          $('#user_password_confirmation').removeClass('green').addClass('red');
        }

      } else if (this_id == 'user_username') {
        $.get('/users/username_check/' + $.trim($(this).val()), function(response) {

          if (response.free) {
            $('#user_username').css({ color: "#1aba00" }).addClass('green');
          } else {
            $('#user_username')
              .animate({ color: "#f5f5f5" }, function() {
                $('#user_username').val('username taken - try again').animate({ color: "#F00" });
              });
          }
        });

      } else {
        if ( $(this).val() != '') {
          $(this).addClass('green');
        } else {
          $(this).removeClass('green');
        }
      }

    });


    $('#user_username').click(function() {
      if ($(this).val() == 'username taken - try again') {
        $(this).css({ color: "#000" }).val('');
      }
    });

  });

app/views/users/history.html.haml
#questions
  .container_16
    .grid_16

      %h1 YOUR HISTORY

      %p
      %h3 Questions you asked
      - if @questions_asked.any?
        - @questions_asked.each do |q|
          %p
            = link_to q.question, question_path(q)
            %span.your_question YOUR QUESTION
      - else
        %p You have not asked any questions yet.

      %p &nbsp;
      %p &nbsp;
      %h3 Questions you answered
      - if @questions_answered.any?
        - @questions_answered.each do |q|
          %p
            = link_to q.question, question_path(q)
            %span.already_voted ALREADY VOTED
      - else
        %p You have not answered any questions yet.

app/views/users/new.html.haml
#login
  .container_16
    .grid_8.suffix_4.prefix_4
      %h4 Registration
      = render 'form'

      .signupnow
        already have an account?
        = link_to "login", login_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Password digest:
  = @user.password_digest
%p
  %b Zip:
  = @user.zip
%p
  %b Dob:
  = @user.dob
%p
  %b Gender:
  = @user.gender

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path