config/routes.rb
Rollpoll::Application.routes.draw do

  resources :topics
  resources :sessions

  resources :questions, except: [:edit, :destroy] do
    get :next, on: :collection
    get :ninja, on: :collection
    resources :answers, only: :show do
      get :vote, on: :member, as: :vote
    end
  end

  resources :users, only: [:new, :index, :create, :show] do
    get :username_check, on: :collection
    get :history, on: :collection
  end

  match '/about' => "pages#about", as: :about
  match '/login' => "sessions#new", as: :login
  match '/logout' => "sessions#destroy", as: :logout
  match '/registration' => "users#new", as: :registration
  match '/users/username_check/:uname' => 'users#username_check'


  namespace :admin do
    resources :administrators
    resources :questions
    resources :users
    resources :sessions

    match '/login' => "sessions#new", as: :login
    match '/logout' => "sessions#destroy", as: :logout

    root :to => 'users#index'
  end

  root :to => 'pages#index'

end

app/views/shared/_header.html.haml
#header

  .header_content
    .container_12
      .grid_2
        .logo= link_to (image_tag 'logo.png'), root_path
      .grid_10
        %ul.nav
          %li
            - if logged_in?
              - if current_page? history_users_path
                = link_to "Logout", logout_path, style: 'color: red'
              - else
                = link_to "Your Account", history_users_path
            - else
              = link_to "Login", login_path
          %li &bull;
          %li= link_to "Random", root_path
          %li &bull;
          %li= link_to "Browse", questions_path
          %li &bull;
          %li= link_to "Ask a Question", new_question_path
          %li &bull;
          %li= link_to "About", about_path

  .header_border