config/routes.rb
Rollpoll::Application.routes.draw do

  resources :topics
  resources :sessions

  resources :questions, except: [:edit, :destroy] do
    get :next, on: :collection
    get :ninja, on: :collection
    resources :answers, only: :show do
      get :vote, on: :member, as: :vote
    end
  end

  resources :users, only: [:new, :index, :create, :show] do
    get :username_check, on: :collection
    get :history, on: :collection
  end

  match '/about' => "pages#about", as: :about
  match '/login' => "sessions#new", as: :login
  match '/logout' => "sessions#destroy", as: :logout
  match '/registration' => "users#new", as: :registration
  match '/users/username_check/:uname' => 'users#username_check'


  namespace :admin do
    resources :administrators
    resources :questions
    resources :users
    resources :sessions

    match '/login' => "sessions#new", as: :login
    match '/logout' => "sessions#destroy", as: :logout

    root :to => 'users#index'
  end

  root :to => 'pages#index'

end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    "admin/application", :media => "all"
    = javascript_include_tag "admin/application"
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = csrf_meta_tags


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          .brand RollPoll Administration
          - unless current_admin.nil?
            %ul.nav
              %li= link_to "Users", admin_users_path
              %li= link_to "Questions", admin_questions_path
              %li= link_to "Administrators", admin_administrators_path

            %ul.nav.pull-right
              %li= link_to "Logout", admin_logout_path

    .container
      .alerts
        - flash.each do |x, y|
          .alert{ class: x }
            = y.to_s

      .main
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    %script{ type: "text/javascript", src: "//use.typekit.net/jtq6zvf.js" }
    %script{ type: "text/javascript" } try{Typekit.load();}catch(e){}
    = csrf_meta_tags

  %body
    = render 'shared/header'
    - if flash.any?
      .container_12
        .grid_10.suffix_1.prefix_1
          - flash.each do |x, y|
            .alert{ class: x }
              = y.to_s
    = yield